name: Build & Release
on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          python -m PyInstaller build.spec --distpath ./dist --workpath ./build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DynamicIsland.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

